name: issue

on:
  issues:
    type: [opend, edited]

jobs:
  git_push:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2
        with: 
          token: ${{ secrets.PAT }}
      - name: push
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GHA"
          git fetch
          date > date.txt
          git add .
          git commit -m "Write datetime."
          git push origin HEAD
      - name: Slack notify(success)
        uses: 8398a7/action-slack@v3
        with:
          status: custom
          custom_payload: |
            {
              color: 'good',
              text: "aaa",
              attachments: [
                {
                  color: 'good',
                  fields: [
                    {
                      title: 'bbb',
                      value: '<https://google.com|${{ github.actor }}>',
                      short: false
                    },
                    {
                      title: 'ddd',
                      value: '`@${{ github.actor }}`',
                      short: false
                    }
                  ]
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_DM_WEBHOOK_URL }}