name: issue

on:
  issues:
    type: [opend, edited]

jobs:
  git_push:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2
        with: 
          persist-credentials: false
      - name: push
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          date > date.txt
          git add .
          git commit -m "Write datetime."
          git push origin HEAD