name: issue

on:
  issues:
    type: [opend, edited]

jobs:
  git_push:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: push
        run: |
          date > /tmp/date.txt
          git add ..
          git commit -m "Write datetime."
          git push origin HEAD