name: mention-to-slack

on:
  issues:
    types: [opened, edited]
  issue_comment:
    types: [created, edited]

jobs:
  mention-to-slack:
    runs-on: ubuntu-latest
    steps:
      - name: Run
        uses: Laurenfrost/mention-to-slack@latest
        with:
          configuration-path: .github/mention-to-slack.yml
          repo-token: ${{ secrets.PAT }}
          slack-webhook-url: ${{ secrets.SLACK_DM_WEBHOOK_URL }}
          bot-name: "Send Mention from BOT"