name: push

on:
  push:

jobs:
  checkout:
    runs-on: ubuntu-latest

    steps:
      - name: Is it merge commit?
        run: |
          ref=${{ github.ref }}
          branch_name=${ref#refs/heads/}
          echo "BRANCH_NAME=$branch_name" >> $GITHUB_ENV
          echo "VERSION_NAME=${branch_name/release\//ver.}" >> $GITHUB_ENV
      - name: echo
        run: |
          echo ${{ env.BRANCH_NAME }}
          echo ${{ env.VERSION_NAME }}