name: push

on:
  push:

jobs:
  checkout:
    runs-on: ubuntu-latest

    steps:
      - name: Is it merge commit?
        run: |
          ref=${{ github.ref }}
          branch_name=${ref#refs/heads/}
          echo "BRANCH_NAME=${ref#refs/heads/}" >> $GITHUB_ENV
      - name: echo
        run: |
          echo ${{ env.BRANCH_NAME }}
          echo ${${{ env.BRANCH_NAME }}/release\//ver.}